### ISSUE TITLE
[fMRIPrep] Preprocessing 

### ISSUE THREAD

**Issue by willstrawson** [htwangtw/adie_ongoingthoughts#26]
fMRI data is not preprocessed. I want to run the data through fMIRprep with minimal preprocessing so the resulting data can be used for any subsequent analysis. I say we deal with gradient-based preprocessing steps (e.g. parcellations) in a different issue.

**Comment by htwangtw** [comment]
Do you want to move anything related to analysis to a new repo? Let's keep this repo strictly for data management.

**Comment by willstrawson** [comment]
see: https://github.com/willstrawson/adie_fmri_preprocessing
